### ISSUE TITLE
Rocks dropping wrong items

### ISSUE THREAD

**Issue by PaladinOne** [lawremi/PerFabricaAdAstra#49]
A few days ago I started a new world using all PFAA veins/forms and no veins from other mods. Over the course of today, I encountered very strange behavior when breaking two blocks: Garnet Sand and Limestone Stone. Limestone Stone drops nothing (in stead of the expected Limestone Cobblestone), except that one time out of 30 blocks, it dropped a piece of Flint. Garnet Sand generally drops nothing, but it has a chance to drop either Silver or Electrum Nuggets. Both of these feel wrong.

Mod list:
Name Version
Minecraft Coder Pack 9.05
Forge Mod Loader 7.10.99.99
Minecraft Forge 10.13.4.1492
AppliedEnergistics2 Core rv2-stable-9
CodeChicken Core 1.0.7.46
Micdoodle8 Core 
Not Enough Items 1.0.5.111
OpenComputers (Core) 1.5.14.30
OpenEye 0.6
Player API 1.2
Thaumic Tinkerer Core 0.1
OpenModsCore 0.7.3
CoFH ASM 000
IndustrialCraft 2 2.2.757-experimental
Advanced Solar Panels 1.7.10-3.5.1
AFSU Mod 1.2.2a-Mustaa
AppleCore 1.1.0
Applied Energistics 2 rv2-stable-9
CoFH Core 1.7.10R3.0.3B2
BuildCraft 7.0.17
BC Factory 7.0.17
BC Energy 7.0.17
BC Silicon 7.0.17
BC Builders 7.0.17
BC Transport 7.0.17
Hardcore Ender Expansion 1.8.2
Forestry for Minecraft 3.6.3.20
Galacticraft Core 3.0.12
Galacticraft Planets 3.0.12
Baubles 1.0.1.10
Thaumcraft 4.2.3.5
Pam's HarvestCraft 1.7.10i
Geologica 0.2.26
Railcraft 9.6.1.15
The Twilight Forest 2.3.7
GregTech MC1710
asielib 0.4.2
Waila 1.5.10
Automagy 0.26.3
Backpack 2.0.1
BD Lib 1.9.1.97
Binnie Core 2.0-pre14
Botany 2.0-pre14
Extra Bees 2.0-pre14
Extra Trees 2.0-pre14
Genetics 2.0-pre14
Blood Magic: Alchemical Wizardry v1.3.3
Blood Arsenal 1.1-14
BC Robotics 7.0.17
BuildCraft Compat 7.0.9
EnderStorage 1.4.7.36
Forge Multipart 1.2.0.345
MrTJPCore 1.1.0.30
ProjectRed Core 4.7.0pre7.91
ProjectRed Transmission 4.7.0pre7.91
OpenComputers 1.5.14.30
Computronics 1.5.6
Build Mod v1.0
CoroPets v1.0
CoroAI v1.0
Extended Renderer v1.0
Extended Mod Config v1.0
Custom Ore Generation 1.2.20
Draconic Evolution 1.0.1c
Electro-Magic Tools 2.0.0Alpha4
Extra Cells 2 2.2.73
FastCraft 1.21
Thaumic Tinkerer unspecified
Forbidden Magic 1.7.10-0.57
Galactic Greg 0.9.1RC2
GalaxySpace 2.3
GemBlocksForGreg 1.5.0
Magic Bees 1.7.10-2.3.3
GenDustry 1.6.0.111
Graviation Suite 1.7.10-2.0.3
Greg's Lighting 1.11.2
HelpFixer 1.0.7
Nuclear Control 2 2.2.5a-GoingForTheKill
Inventory Tweaks 1.59-dev-156-af3bc68
Iron Chest 6.0.62.742
Iron Chest Minecarts 1.0.3
JABBA 1.2.1
JourneyMap @JMVERSION@
LunatriusCore 1.1.2.21
NEI Addons 1.12.11.36
NEI Addons: Developer Tools 1.12.11.36
NEI Addons: Applied Energistics 2 1.12.11.36
NEI Addons: Botany 1.12.11.36
NEI Addons: Forestry 1.12.11.36
NEI Addons: Crafting Tables 1.12.11.36
NEI Addons: Ex Nihilo 1.12.11.36
NEI Integration 1.0.10a
NodalMechanics 1.7.10R1.0
NotEnoughCodecs 0.3
NotEnoughKEys @MOD_VERSION@
OpenMods 0.7.3
OpenBlocks 1.4.3
OpenPrinter 0.1.0.120
OpenSecurity 1.0.58
Pam's Harvest the Nether 1.7.10
Chemica 0.2.26
Project Blue 1.1.4
ProjectRed Transportation 4.7.0pre7.91
ProjectRed Exploration 4.7.0pre7.91
ProjectRed Compatibility 4.7.0pre7.91
ProjectRed Integration 4.7.0pre7.91
ProjectRed Fabrication 4.7.0pre7.91
ProjectRed Illumination 4.7.0pre7.91
ProjectRed Expansion 4.7.0pre7.91
Roguelike Dungeons 1.3.6.3
Schematica 1.7.6.121
The Spice of Life 1.2.3
Steve's Factory Manager A93
Steve's Addons 0.10.15
Steve's Carts 2 2.0.0.b18
Storage Drawers 1.7.10-1.5.12
Tainted Magic 1.1.5.4
TC Node Tracker 1.1.2
Thaumcraft Mob Aspects 1.7.x-2B
Thaumcraft NEI Plugin @VERSION@
Thaumic Machina 0.2.1
Thaumic Energistics 0.8.10.8
Thaumic Exploration 0.6.0
Thaumic Horizons 1.1.5
Waila Harvestability 1.1.2
WarpTheory 1.7.10R1.0e.Custom
WR-CBE Core 1.4.1.9
WR-CBE Addons 1.4.1.9
WR-CBE Logic 1.4.1.9
YAMCore 0.5.2
Minecraft Multipart Plugin 1.2.0.345
ForgeRelocation 0.0.1.3
MCFrames 1.0
RelocationFMP 0.0.1.2
Hunger Overhaul 1.7.10-1.0.0.jenkins75
Forge Microblocks 1.2.0.345

**Comment by lawremi** [comment]
This was fixed with the fix for #47. Will release a new version this weekend.

**Comment by PaladinOne** [comment]
I was testing it again in an instance that contained only PFAA (NEI) and GregTech, and an instance that contained only PFAA (and NEI) and confirmed that the issue was still present (to eliminate the possibility that some other mod was causing it).

However, that it is fixed is good to hear and makes my extra test a little irrelevant.
